/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dn_tim_dntimlsn12bspatch_BsPatch */

#ifndef _Included_com_dn_tim_dntimlsn12bspatch_BsPatch
#define _Included_com_dn_tim_dntimlsn12bspatch_BsPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dn_tim_dntimlsn12bspatch_BsPatch
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xuesong_bspacthdemo_MainActivity_bspatch
        (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
